spring.application.name=tenant-service

server.port=8083

# Database
spring.datasource.url=jdbc:mariadb://localhost:3306/smartroomms
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=U21hcnRSb29tTVMtU2VjcmV0LUtleS0yMDI2LVZlcnlMb25nU2VjdXJlU3RyaW5n
jwt.expiration=86400000

# Logging
logging.file.name=logs/tenant-service.log
logging.level.com.project.tenantservice=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n